---
# group_vars/all.yaml
gcp_service_account: ansible-secret-manager@twitter-backup-371709.iam.gserviceaccount.com
gcp_credentials_file: "/home/koffcheg/twitter-backup-371709-6ea59b4f2f20.json"
gcp_project_id: twitter-backup-371709
eco_secrets_gcp_secret_name: eco-boutique-secrets
gcp_secrets_prefix: vpn-client-

client_configs_base_dir: "/home/koffcheg/client-configs"
client_meta_dir: "/home/koffcheg/client-meta"
client_archives_dir: "{{ client_configs_base_dir }}/archives"

# Only relevant to the server
easy_rsa_dir: /home/kharkov501/easy-rsa
ta_key_path: /etc/openvpn/ta.key
openvpn_config_dir: /etc/openvpn

factory_client_config_dir: /tmp/client-configs

jetson_docker_version: "26.1.3"
jetson_docker_url: "https://download.docker.com/linux/static/stable/aarch64/docker-26.1.3.tgz"
