# roles/jetson_docker_engine/defaults/main.yaml
---

# Docker static binary version / arch
jetson_docker_version: "26.1.3"
jetson_docker_arch: "aarch64"

# Download URL for static tarball (update if you use another source)
jetson_docker_url: "https://download.docker.com/linux/static/stable/{{ jetson_docker_arch }}/docker-{{ jetson_docker_version }}.tgz"

# Where to install the binaries
jetson_docker_bin_dir: "/usr/local/bin"

# Systemd unit path
jetson_docker_unit_path: "/etc/systemd/system/docker.service"

# Docker daemon config
jetson_docker_daemon_dir: "/etc/docker"
jetson_docker_daemon_config: "/etc/docker/daemon.json"

# Docker data root
jetson_docker_data_root: "/var/lib/docker"
