# roles/monitoring_prometheus_config/handlers/main.yml

- name: Reload Prometheus
  service:
    name: "{{ monitoring_prometheus_service_name }}"
    state: reloaded
  when: monitoring_prometheus_reload | bool
