# roles/monitoring_prometheus_config/handlers/main.yml

- name: Reload Prometheus
  service:
    name: "{{ monitoring_prometheus_service_name }}"
    state: restarted
    enabled: true
  listen: "reload prometheus"
  when: monitoring_prometheus_reload | bool
