# roles/jetson_docker_engine/handlers/main.yaml

- name: reload systemd for docker
  become: true
  systemd:
    daemon_reload: true

- name: restart docker
  become: true
  systemd:
    name: docker.service
    state: restarted
